# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kodkollektivet.managers.UserManager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=254)),
                ('last_name', models.CharField(blank=True, max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'baseuser',
                'verbose_name_plural': 'baseusers',
            },
            managers=[
                ('objects', kodkollektivet.managers.UserManager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Markdown syntax can be used!')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('publish', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Event post',
                'ordering': ['-created_date'],
                'verbose_name_plural': 'Event posts',
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProCon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Project-Contributor relation',
            },
        ),
        migrations.CreateModel(
            name='ProFra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Framework')),
            ],
            options={
                'verbose_name': 'Project-Framework relation',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('gh_name', models.CharField(blank=True, max_length=254)),
                ('gh_id', models.IntegerField(blank=True, null=True)),
                ('gh_url', models.CharField(blank=True, max_length=254)),
                ('gh_readme', models.TextField(blank=True, help_text='Project readme. Markdown syntax!')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ProLan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Project')),
            ],
            options={
                'verbose_name': 'Project-Language relation',
            },
        ),
        migrations.CreateModel(
            name='ProRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Project')),
            ],
            options={
                'verbose_name': 'Project-Role-Contributor relation',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=254)),
                ('slug', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.CharField(blank=True, max_length=254, null=True)),
                ('website', models.CharField(blank=True, max_length=254, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=254, null=True)),
                ('about', models.TextField(blank=True, help_text='Markdown syntax', null=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('date_paid', models.DateTimeField(null=True, verbose_name='date paid')),
                ('gh_login', models.CharField(max_length=254, null=True)),
                ('gh_url', models.CharField(max_length=254, null=True)),
                ('gh_id', models.IntegerField(null=True)),
                ('gh_html', models.CharField(blank=True, max_length=254, null=True)),
                ('gh_avatar', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['slug'],
            },
            bases=('kodkollektivet.baseuser',),
        ),
        migrations.AddField(
            model_name='prorol',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Role'),
        ),
        migrations.AddField(
            model_name='profra',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Project'),
        ),
        migrations.AddField(
            model_name='procon',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Project'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='prorol',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Contributor'),
        ),
        migrations.AddField(
            model_name='procon',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Contributor'),
        ),
    ]
